Change after each to close server
Otherwise cannot be use with mocha watch because the address would be in use.
yarn test -- --watch
1) /hello returns JSON:
     Error: ECONNREFUSED: Connection refused